apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: starter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: starter-deployment
  minReplicas: 1
  maxReplicas: 40
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
      selectPolicy: Min
  metrics:
    - type: Pods
      pods:
        metric:
          name: custom-metric
        target:
          type: AverageValue
          averageValue: 0.98