apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: starter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: starter-deployment
  minReplicas: 1
  maxReplicas: 9
  metrics:
    - type: Pods
      pods:
        metric:
          name: bajajanirudh-custom-metric
        target:
          type: AverageValue
          averageValue: 0.6